[borg_server]
borg-server ansible_host=192.168.1.46 ansible_user=vagrant ansible_ssh_private_key_file=/home/vagrant/.ssh/vagrant_keys/borg-server.key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[borg_client]
borg-client ansible_connection=local

[apache_server]
apache-server ansible_host=192.168.1.42 ansible_user=root ansible_ssh_private_key_file=/home/vagrant/.ssh/apache-server.key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[samba_server]
samba-server ansible_host=192.168.1.44 ansible_user=root ansible_ssh_private_key_file=/home/vagrant/.ssh/samba-server.key ansible_ssh_common_args='-o StrictHostKeyChecking=no'
